name: oppgave 16

on:

  workflow_dispatch:
    

jobs:
  job1:
    defaults:
      run:
        shell: pwsh
        working-directory: ${{ github.workspace }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          enable-AzPSSession: true
 
      - name: Install and cache PowerShell modules
        uses: potatoqualitee/psmodulecache@v4
        with:
          modules-to-cache: Az.Storage, Az.Functions, Az.Websites, Az.Resources, Az.Accounts

      - name: 'Run cleanup script'
        uses: azure/powershell@v1
        with:
          inlineScript: ./funcApp/cleanup.ps1
          azPSVersion: "latest"

      - name: 'logout from azure'
        uses: azure/powershell@v1
        with:
          inlineScript: |
            Disconnect-AzAccount -Scope CurrentUser
            az logout
            az cache purge
            az account clear
          azPSVersion: "latest" 